export default {
  CHANGE_SONG_TITLE: "SONG/CHANGE_TITLE",
  CHANGE_SONG_ARTIST: "SONG/CHANGE_ARTIST",
  //CHORD
  ADD_NEW_CHORD: "SONG/ADD_NEW_CHORD",
  CHANGE_CHORD_KEY: "SONG/CHANGE_CHORD",
  //SECTION
  ADD_NEW_SECTION: "SONG/ADD_NEW_SECTION",
  DELETE_SECTION: "SONG/DELETE_SECTION",
  CHANGE_SECTION_TITLE: "SONG/CHANGE_SECTION_TITLE"
};
