export default {
  //CHORD
  ADD_NEW_CHORD: "SONG/ADD_NEW_CHORD",
  CHANGE_CHORD_KEY: "SONG/CHANGE_CHORD",
  DELETE_CHORD: "SONG/DELETE_CHORD",
  //SECTION
  ADD_NEW_SECTION: "SONG/ADD_NEW_SECTION",
  DELETE_SECTION: "SONG/DELETE_SECTION",
  CHANGE_SECTION_TITLE: "SONG/CHANGE_SECTION_TITLE",
  //SONG
  CHANGE_SONG: "SONG/CHANGE_SONG",
  CHANGE_SONG_TITLE: "SONG/CHANGE_SONG_TITLE",
  CHANGE_SONG_ARTIST: "SONG/CHANGE_SONG_ARTIST",
  TONE_UP: "SONG/TONE_UP",
  TONE_DOWN: "SONG/TONE_DOWN",
  //SAVE SONG
  SAVE_SONG_STATE: "SONG/SAVE_SONG_STATE",
  SAVE_SONG_DB: "SONG/SAVE_SONG_DB",
  FETCH_SAVED_SONG: "SONG/FETCH_SAVED_SONG",
  UPDATE_SAVED_SONG: "SONG/UPDATE_SAVED_SONG",
  NEW_SONG: "SONG/NEW_SONG",
  DELETE_SONG: "SONG/DELETE_SONG"
};
