export default {
  SHOW_CHORD_CHANGE: "COMPONENTS/SHOW_CHANGE_CHORD",
  CLOSE_MODAL: "COMPONENTS/CLOSE_MODAL",
  SONG_DROPDOWN_HOVER: "COMPONENTS/SONG_DROPDOWN_HOVER",
  SONG_DROPDOWN_UNHOVER: "COMPONENTS/SONG_DROPDOWN_UNHOVER"
};
